dist: bionic
language: python
cache: pip

addons:
  postgresql: "9.6"

matrix:
  include:
   - env: TOXENV=py37-dj22-wa27-postgres
     python: 3.7

   - env: TOXENV=py37-dj22-wa26-postgres
     python: 3.7

   - env: TOXENV=py38-dj22-wa27-postgres
     python: 3.8

   - env: TOXENV=py37-dj22-wa27-sqlite
     python: 3.7

install:
  - sudo apt-get install -y libgit2-dev
  - pip install tox

script:
  - tox
